[package]
name = "hls-video-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
reqwest = { version = "0.12.12", features = ["blocking"] }
clap = { version = "4.5.31", features = ["derive"] }
rayon = "1.10.0"
